name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Make executable - Linux
        run: |
          sudo apt-get install libgl1-mesa-dev libxcursor-dev
          go build -o pmsim main.go
        timeout-minutes: 10
        if: matrix.os == 'ubuntu-latest'
      - name: Make executable - MacOS
        run: |
          go build -o pmsim main.go
        timeout-minutes: 10
        if: matrix.os == 'macos-latest'
      - name: Make executable - Windows
        run: |
          go build -o pmsim.exe main.go
        timeout-minutes: 10
        if: matrix.os == 'windows-latest'
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./pmsim*", "./scripts/*"]'
